### ISSUE TITLE
outdated comment

### ISSUE THREAD

**Issue by TheTechRobo** [Elive/eltrans#11]
`# FIXME: do not allow translations when the english is not reviewed yet, at least a minimum (and warning when there's remaining ones)` on line 2

this is not implemented?

**Comment by Thanatermesis** [comment]
yes, there's many, fixmes, and todo's in comments that are not really updated... in fact to add those notes in the source code is not the best place to keep a "track" of them lol

**Comment by TheTechRobo** [comment]
Try the projects tab? It would be much easier to keep track of in the github project boards

**Comment by TheTechRobo** [comment]
https://github.com/Elive/eltrans/projects is the link to Projects tab

**Comment by Thanatermesis** [comment]
Ah, didn't know this feature of github! but I already use many tracking systems, for example the BTS, Asana for own organization of tasks, mindomo for sorting working tasks, and recently, switched the last one to a simple plain file with sections and tabs lol

**Comment by TheTechRobo** [comment]
haha

actually thats a lot of services, what's the difference between 

> sorting working tasks

and

> organization of tasks

??

(Also, GH Projects is free :smirk:)
