### ISSUE TITLE
Questioning the logic from lines 38 to 45

### ISSUE THREAD

**Issue by TheTechRobo** [Elive/eltrans#12]
```
    if [[ "$ui_user_answered" = "cancel" ]] ; then
        if [[ -n "$EROOT" ]] ; then
            el_notify normal znes "Eltrans" "$( eval_gettext "Thanks for collaborating with the Elive translations." )"
        else
            el_notify normal "/usr/share/git-watcher/images/ttc.gif" "Eltrans" "$( eval_gettext "Thanks for collaborating with the Elive translations." )"
        fi
        exit 0
    fi
```
The thing I don't get is the else there. Why should it display the spinning box instead of the 1-up if the user did...something else??? I no longer _ever_ see the 1-up. According to `git blame`, three months ago you did "small improvements" on that block where you switched from a window to a notification. What is `$EROOT`? (Also, I think that if the user clicks exit at the language selection screen it shouldn't show the thanks message as thanks for what? Launching eltrans?)

**Comment by Thanatermesis** [comment]
Heh, i dont remember this code but apparently its just like: if you are in E16, show a normal image, if you are in E24 (or more exactly "something else"), show an animated gif (which should be supported by the notificator of E24

in the end, nothing important, just a funny feature to see (animated motivational images in the notification)

**Comment by TheTechRobo** [comment]
Oh, that makes sense. :)
