### ISSUE TITLE
Not a fan of the 80% limit

### ISSUE THREAD

**Issue by TheTechRobo** [Elive/eltrans#13]
I really don't like the 80% limit for proofreading. Like when  it's below that, you NEED proofreading! 

It really makes me want to submit those files with not so legit tricks :face_with_head_bandage: ...though I wouldn't, because I repsect your wishes.

**Comment by Thanatermesis** [comment]
well, it is for a reason :) of course I would like it to be proofreader and then I will not have to do this work, but the first proofreading needs a specific process and I want to make sure that it has been made, note that **then it can perfectly proofreaded** (again) and improved, but it requires a first step before

the thing is that after all the apps has been first-proofreaded, they are like "enabled" in eltrans (even for English) :)

**Comment by TheTechRobo** [comment]
Hm, I'd really like to contribute ... could I have access to the pre-80% thingy? I will use that google translate method, and now that I'm back in classes I'm a lot less rusty in French.
