### ISSUE TITLE
Exits prematurely after asking about proofreading

### ISSUE THREAD

**Issue by TheTechRobo** [Elive/eltrans#8]
So I want to translate French. While I was testing ELTRANS, I selected one that "needs more english proofreading (0% done). I click it, it tells me i cant, it asks me if I want to learn about the reverse-engineer trick, I click NO...

And then it just exits.

I ran it from a terminal, and after I clicked No it brought me back to the command prompt. 

This may be confusing for new translators...?

**Comment by TheTechRobo** [comment]
(NOTE: zsh reports exit code of 0 after it exits prematurely, so its not an error)

**Comment by TheTechRobo** [comment]
UPDATE: Just tested and even if I click YES at the dialog, it opens up chromium (which i wish was firefox, how do i change this?) and then eltrans quits

**Comment by Thanatermesis** [comment]
fixed in last version

**Comment by TheTechRobo** [comment]
I just saw! Nice job :D
