### ISSUE TITLE
While creating a new language code, repeat dialogs

### ISSUE THREAD

**Issue by TheTechRobo** [Elive/eltrans#9]
To test (I was going to remove my translations dir after) I typed `en_CA` into eltrans language select. It asked if I wanted to create, I said yes.It showed this message

> This is a new language which didn't existed previously for this translation, so we are going to create a new template for this type of language.

Then it showed this message AGAIN

> Please confirm first. Is the language identifier that you inserted the correct for your translations? 'en_CA'

And the loop went over and over. I assume this is a bug.

**Comment by TheTechRobo** [comment]
(UPDATE: Apart from the `Did not receive a reply` messages that appear with all zenity programs (including THUNAR), Terminology displays this info:)

```
(zenity:1826): Gtk-CRITICAL **: 15:45:42.046: gtk_main_quit: assertion 'main_loops != NULL' failed

(zenity:1826): Gtk-CRITICAL **: 15:45:43.015: gtk_main_quit: assertion 'main_loops != NULL' failed

(zenity:1826): Gtk-CRITICAL **: 15:45:45.186: gtk_main_quit: assertion 'main_loops != NULL' failed

(zenity:1826): Gtk-CRITICAL **: 15:45:45.186: gtk_main_quit: assertion 'main_loops != NULL' failed

(zenity:1826): GLib-CRITICAL **: 15:45:51.608: Source ID 217 was not found when attempting to remove it
```
By now I had clicked OK on the "Counting translated messages..." and force-quit (by shift-click the close button) the "please confirm" (because the buttons had stopped doing anything--they were clickable but there was no effect), and now zenity displayed: 

> Please run again Eltrans selecting a different language to use.

**Comment by TheTechRobo** [comment]
I just tested it again and terminology displays on the first few prompts: 

```
A         Projects/translations/elive/elive-tools/en_CA.po
E: /home/thetechrobo/Projects/translations/elive/elive-upgrader/en_CA.po doesn't exist
```

But this time, After like ten of each box (like confirmation and "Were going to create a template") it opened the "Select an element" and the buttons were clickable the whole time. I also didnt get the assertion `!=` error. :thinking:

**Comment by Thanatermesis** [comment]
not tested but bug seems solved

also a message about "when" sublanguages needs to be used has been added

**Comment by TheTechRobo** [comment]
> Warning: This is a new language translation which didn't existed previously, a sublanguage or dialect should be only used when the main language is not compatible with the messages, like when needs using different sentences or meanings, otherwise is better to simply use the main language.

But in terminology...

```
(zenity:10929): Gtk-CRITICAL **: 12:35:37.426: gtk_main_quit: assertion 'main_loops != NULL' failed

(zenity:10929): Gtk-CRITICAL **: 12:35:40.007: gtk_main_quit: assertion 'main_loops != NULL' failed

(zenity:10929): Gtk-CRITICAL **: 12:35:40.992: gtk_main_quit: assertion 'main_loops != NULL' failed

(zenity:10929): Gtk-CRITICAL **: 12:35:41.709: gtk_main_quit: assertion 'main_loops != NULL' failed

(zenity:10929): Gtk-CRITICAL **: 12:35:42.444: gtk_main_quit: assertion 'main_loops != NULL' failed

(zenity:10929): GLib-CRITICAL **: 12:35:46.333: Source ID 743 was not found when attempting to remove it
```

However it does work, there are just those errors... :baffled:

**Comment by Thanatermesis** [comment]
> However it does work, there are just those errors... :baffled:

You can perfectly ignore all the "zenity" error messages, there seems to be something wrong working on zenity but it simply works, zenity errors are simply not important and can be perfectly ignored

**Comment by TheTechRobo** [comment]
> You can perfectly ignore all the "zenity" error messages, there seems to be something wrong working on zenity but it simply works, zenity errors are simply not important and can be perfectly ignored

Sounds good :D
